### ISSUE TITLE
Quad is marked as server only on modrinth

### ISSUE THREAD

**Issue by amyfromearth** [LieOnLion/Quad#1]
Hi, 

This mod is marked as "server" on modrinth which means it doesn't automatically install on client when placed in a modpack resulting in a failure to launch the game because of a missing dependency. 

Could you please set it as "client and server" so it will install automatically when using modpacks?

Thanks!

**Comment by lieonlion** [comment]
Sorry about this, I was unable to set client to be required when getting the mod uploaded, I have changed it now

**Comment by amyfromearth** [comment]
Awesome, thanks!
