### ISSUE TITLE
Quad in Modrinth is "Server" side, but it's required to launch Client

### ISSUE THREAD

**Issue by Blaxe97** [LieOnLion/Quad#10]
![image](https://github.com/user-attachments/assets/19abcc7c-1398-4717-8dc3-81a4bf6cdeb3)
![image](https://github.com/user-attachments/assets/705dc81c-c5e6-4a61-aa80-48488c0cb31d)
Context: I'm making a modpack in which Quad is included in the Exaroton server, but my client needs it to launch

**Comment by lieonlion** [comment]
I have changed it to "Client or Server". 
The problem being that Quad is a server sided mod, so vanilla clients can join on a server with it, so I would like to market it that way. but I do require it on clients for my other mods
