### ISSUE TITLE
Blast furnace recipe broken

### ISSUE THREAD

**Issue by parmerinha99** [LieOnLion/Quad#11]
The mod has conflicts with other libs, which ends up breaking the blast furnace recipe. (1.21 Neoforge)

I disabled all my mods and left only the libs and apis enabled, and several of them conflict with Quad, even libIPN, which only manages the game's interface.

Some don't conflict if I only turn it on and Quad, but if I turn on others, almost randomly, it breaks the recipe.

If I also activate all of them and don't activate Quad, the recipe doesn't break.

Is there any way to disable the management of this recipe in Quad?

I did the tests in a binary way: activating, entering the game and checking the recipe (all of this in new worlds)
![image](https://github.com/user-attachments/assets/ad7cb057-8f44-4f1a-ad3e-9c37e26849d5)

**Comment by lieonlion** [comment]
Can you specify what mods seem to be causing the issue with Quad

**Comment by YuRaNnNzZZ** [comment]
https://github.com/LieOnLion/Quad/blob/8b173526e7729da16cf56b2a5c44b051e630e4db/src/main/resources/data/minecraft/recipe/blast_furnace.json#L9

It's this mod, assuming `forge` ingot tag for neoforge (which uses `c` for tags like fabric)

**Comment by lieonlion** [comment]
> https://github.com/LieOnLion/Quad/blob/8b173526e7729da16cf56b2a5c44b051e630e4db/src/main/resources/data/minecraft/recipe/blast_furnace.json#L9
> 
> It's this mod, assuming `forge` ingot tag for neoforge (which uses `c` for tags like fabric)

yes i know what my mod does, but another mod has to be messing with the tag

**Comment by YuRaNnNzZZ** [comment]
> yes i know what my mod does, but another mod has to be messing with the tag

In 1.21 NeoForge there are no tags under `forge` namespace, at all.

**Comment by lieonlion** [comment]
Sorry, does look to be my mistake, a fix should be out now
