### ISSUE TITLE
[Suggestion] Add support for ignitible items added by Twilight Forest and Supplementaries

### ISSUE THREAD

**Issue by pinkygrocket** [LieOnLion/Quad#14]
Twilight Forest adds mob heads with candles on them, while Supplementaries adds candle holders and makes gunpowder placeable (with placed gunpowder able to be ignited). Crossmod support would be nice to have, so that Quad can help modpack devs bridge mods together.

**Comment by lieonlion** [comment]
If you want the items to light TNT when right clicked, its as easy as adding them to one of the Quad tags. If thats not what you want, can you please elaborate more. :)

**Comment by pinkygrocket** [comment]
I'd like Quad's fire_lighter tag to support igniting more blocks than just vanilla blocks.
