### ISSUE TITLE
[doc] Minor typos on Modrinth page

### ISSUE THREAD

**Issue by hatkidchan** [LieOnLion/Quad#4]
Diff:
```diff
diff --git a/tmp/quad-modrinth.md b/tmp/quad-fixed.md
index 6bb4897..0594f11 100644
--- a/tmp/quad-modrinth.md
+++ b/tmp/quad-fixed.md
@@ -19,7 +19,7 @@

 located in `data/quad/tags/items` (.json files)

-- `immune_all` be added to all `innume_*` tags
+- `immune_all` be added to all `immune_*` tags
 - `immune_cactus` items won't get destroyed by cacti
 - `immune_explosion` items won't get destroyed by explosions
 - `immune_fire` items won't get destroyed by fire/lava
@@ -79,7 +79,6 @@ tags located in `data/c/tags/items` (.json files)
 - ***Brush*** - replaced item `minecraft:copper_ingot` with tag `copper_ingots`
 - ***Lightning Rod*** - replaced item `minecraft:copper_ingot` with tag `copper_ingots`
 - ***Spyglass*** - replaced item `minecraft:copper_ingot` with tag `copper_ingots`
-- > replaced item `minecraft:amethyst_shard` with tag `amethyst_shards`
 - ***Calibrated Sculk Sensor*** - replaced item `minecraft:amethyst_shard` with tag `amethyst_shards`
 - ***Tinted Glass*** - replaced item `minecraft:amethyst_shard` with tag `amethyst_shards`
 ##
```

**Comment by lieonlion** [comment]
fixed the `immune_*`, but whats with the 
"-- > replaced item `minecraft:amethyst_shard` with tag `amethyst_shards`" line in red?

**Comment by hatkidchan** [comment]
![image](https://github.com/LieOnLion/Quad/assets/35804000/eab5c205-95eb-43e2-a6aa-897a3cc63406)
this thing
also missed one after hopper with iron_ingot

**Comment by lieonlion** [comment]
what are you changing though?

**Comment by hatkidchan** [comment]
removing broken list entry?

**Comment by lieonlion** [comment]
why removing it?

**Comment by hatkidchan** [comment]
![image](https://github.com/LieOnLion/Quad/assets/35804000/e0f34889-14c1-49d6-88e0-f0dd13e4d37c)

because it probably shouldn't be here? maybe you just forgot to add the item name here and it made a broken entry in the list. what is it supposed to be?

**Comment by lieonlion** [comment]
its cuz it replace it for the hopper? im not doing the name twice, same with the spyglass, it gets the copper and amethyst shard changed

**Comment by lieonlion** [comment]
thats why its got the pop out with the `- >` in the code, to show its part of the 1 above, unless that isn't clear

**Comment by hatkidchan** [comment]
ah, fair enough, sorry. maybe doing them on one line would be more intuitive?
