### ISSUE TITLE
tnt crash

### ISSUE THREAD

**Issue by Natedogwoooof** [LieOnLion/Quad#5]
[crash-2024-03-15_09.44.22-client.txt](https://github.com/LieOnLion/Quad/files/14617126/crash-2024-03-15_09.44.22-client.txt)

game crashes when loading up idk if its quads fault

**Comment by lieonlion** [comment]
I am doing a rework on the mixins.
version 1.1.2 should fix the issue, it will be releasing soon

**Comment by lieonlion** [comment]
should be fixed now with 1.1.3 :)) create a new issue if its not
