### ISSUE TITLE
tnt is spawning 2 entities when lit by a player

### ISSUE THREAD

**Issue by 800020h** [LieOnLion/Quad#7]
minecraft 1.20.1
fabric loader 0.15.10
fabric API 0.92.1+1.20.1
Quad 1.2.2+1.20.4-Fabric
and many others

tnt is spawning 2 entities when lit by a player

I tried with flint and steel and with fire charge

lighting it with redstone only spawned 1 entity

**Comment by lieonlion** [comment]
I will add the fix in 1.2.3, thank you for bringing this up

**Comment by lieonlion** [comment]
1.2.3 has fixed the issue
