### ISSUE TITLE
Latest update makes fuel no longer work for furnaces [1.20.1]

### ISSUE THREAD

**Issue by MEuph** [LieOnLion/Quad#8]
The latest update caused coal and charcoal to no longer work as fuel in any smelter/cooker. I did not test any other fuel sources, but disabling Quad fixed the issue.

My modlist is:
- Advanced Mining Dimension
- Alchemistry
- AlchemyLib
- Alex's Delights
- Alex's Mobs
- Amendments
- Applied Energistics 2
- Architectury
- Artifacts
- AttributeFix
- Biome Makeover
- Biomes O'Plenty
- Biomes O'Plenty Create Rose Quartz Compat
- Bookshelf
- Building-Gadgets
- Caelus API
- Carry On
- ChemLib
- Chisels & Bits
- Citadel
- Cloth Config
- Collective
- Create
- Create Crafts & Additions
- Create Enchantment Industries
- Create Slice & Dice
- Create: Steam & Rails
- Cristel Lib
- Curios API
- Delightful
- Elytra Slot
- Embeddium
- Enchantment Descriptions
- Explorer's Compass
- Farmer's Delight
- Jade
- Just Enough Items
- Kotlin for Forge
- Lootr
- All Macaw's mods + BOP Compat
- Moonlight Lib
- More Mob Variants
- More Villagers
- Mouse Tweaks
- MrCrayfish's Furniture Mod
- Nature's Compass
- Not Enough Animations
- Oculus
- Polymorph
- Quark
- Sophisticated Backpacks
- Sophisticated Core
- Supplementaries
- TerraBlender
- The Twilight Forest
- Towns and Towers
- Traveler's Backpack
- Tree Harvester (Serilum)
- Twilight's Flavors & Delights
- Vein Mining
- Wares
- Xaero's Minimap
- Xaero's Worldmap
- Yung's API
- Yung's Better Dungeons
- Zeta

**Comment by lieonlion** [comment]
forge or fabric? as they have 2 different systems for fuel registry

**Comment by lieonlion** [comment]
never mind, I saw "Kotlin for Forge"

**Comment by lieonlion** [comment]
fixed in 1.2.5
